# Generated by Django 6.1.1 on 2026-10-04 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('self_description', models.TextField(blank=True, null=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('technical_questions', models.JSONField(blank=True, default=list)),
                ('behavioral_questions', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('preparation_plan', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
